apiVersion: apps/v1
kind: Deployment
metadata:
  name:  <APPLICATIONNAME>
  namespace: <NAMESPACE>
  labels:
    app: <APPLICATIONNAME>-oisp-testsensor-sensor
spec:
  selector:
    matchLabels:
      app: <APPLICATIONNAME>-oisp-testsensor-sensor
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: <APPLICATIONNAME>-oisp-testsensor-sensor
    spec:
      containers:
      - name: busybox
        image: docker.io/busybox:latest
        imagePullPolicy: Always
        command: ["sleep"]
        args: ["100000000"]
      - name: oisp-iot-agent
        env:
          - name: OISP_DEVICE_ID
            value: "<APPLICATIONNAME>"
          - name: OISP_DEVICE_ACTIVATION_CODE
            valueFrom:
              secretKeyRef:
                name: global-devices-secret
                key: activation-code
        volumeMounts:
          - name: oisp-devices-config-volume
            mountPath: /volume/config
          - name: oisp-devices-data-volume
            mountPath: /volume/data
        image: docker.io/oisp/oisp-iot-agent:v2.1.3
        imagePullPolicy: Always
      - name: fusiongatewayapp
        image: docker.io/ibn40/fusiongatewayapp-new:latest
        resources:
          limits:
        volumeMounts:
          - name: gateway-config
            mountPath: /app/resources/application.yaml
            subPath: application.yaml
        imagePullPolicy: Always
      - name: fusionscriptservice
        image: docker.io/ibn40/fusionscriptservice-new:latest
        env:
          - name: FUSION_PORT
            value: "8085"
          - name: FUSION_DOWNSTREAM_URL
            value: "http://gatewayapp:8080/"
          - name: FUSION_DOWNSTREAM_HOST
            value: "gatewayapp"
        imagePullPolicy: Always
        volumeMounts:
          - name: scriptservice-config
            mountPath: /app/resources/application.yaml
            subPath: application.yaml
      - name: fusionmqttdataservice
        image: docker.io/ibn40/fusionmqttdataservice-new:latest
        imagePullPolicy: Always
        volumeMounts:
          - name: mqttservice-config
            mountPath: /app/resources/application.yaml
            subPath: application.yaml
      volumes:
        - name: oisp-devices-config-volume
          configMap:
            name: global-devices-config
            items:
            - key: config.json
              path: config.json
        - name: gateway-config
          configMap:
            name: <APPLICATIONNAME>-app-config
            items:
            - key: application.yaml
              path: application.yaml
        - name: mqttservice-config
          configMap:
            name: <APPLICATIONNAME>-app-config2
            items:
            - key: fusionmqttdataservice_application.yaml
              path: application.yaml
        - name: scriptservice-config
          configMap:
            name: <APPLICATIONNAME>-app-config3
            items:
            - key: fusionscriptservice_application.yaml
              path: application.yaml
        - name: oisp-devices-data-volume
          persistentVolumeClaim:
            claimName: <APPLICATIONNAME>-pvc-device-data
      imagePullSecrets:
      - name: regcred
      nodeSelector:
        kubernetes.io/hostname: <NODENAME>
